### ISSUE TITLE
[feature request] Build arm64 image

### ISSUE THREAD

**Issue by druchoo** [komodorio/komoplane#23]
Hello can you build arm64 image please. If possible mirroring to Quay and Public ECR would be great also.

Thanks

**Comment by undera** [comment]
Hey
Thanks for the feedback. That won't be too hard to make the arm64 image. Mirroring to Quay/ECT is a bit ouf ot my knowledge at the moment.

**Comment by druchoo** [comment]
Hi @undera, thanks for looking into this and the great project!

Publishing to other container registries would just require an account and adding to your [Github actions](https://github.com/komodorio/komoplane/blob/main/.github/workflows/release.yaml#L60-L89) to login and push there. 

Github Container registry (ghcr.io) is also another option. It wouldn't require another account so should be a bit simpler to implement.

Here's an example:
* https://github.com/salesforce/sloop/blob/master/.github/workflows/publish.yml

And official docs:
* https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

**Comment by undera** [comment]
For the start, I've added ARM image building

**Comment by undera** [comment]
I have published release 0.0.8, it should have ARM64 image built for it
