### ISSUE TITLE
Slack workspace seems closed to joiners?

### ISSUE THREAD

**Issue by arichtman-srt** [komodorio/komoplane#49]
Not sure if this is intentional or not but Slack doesn't want to let me join

![image](https://github.com/komodorio/komoplane/assets/121832558/06ddd97a-86f9-4811-8125-07df4babf5f8)

**Comment by undera** [comment]
This is more a question to  Slack support, probably something between your multiple email accounts... If it does not work for you at all - just ask your Komoplane questions here in issue tracker.

**Comment by arichtman-srt** [comment]
Ok, thanks!
