### ISSUE TITLE
Wrong plural name for "Policy" API resource

### ISSUE THREAD

**Issue by okorzhov** [komodorio/komoplane#65]
We use the latest Komoplane version and it seems have an issue while calling managed resource "Policy"
UI indicates the next error when attempts to open Policy resource: "Failed: Error: Failed to fetch data from API. Status code: 500"  and komoplane shows next error it its log:
`time="2024-08-06T13:43:51Z" level=warning msg="HTTP 500 0s - GET /api/managed/iam.aws.upbound.io/v1beta1/Policy/test-policy-v6q2r-nz9vx?full=1: the server could not find the requested resource (get policys.iam.aws.upbound.io test-policy-v6q2r-nz9vx)"
`  
I suppose that issue caused by wrongly calling API resource Policy (iam.aws.upbound.io/v1beta1). Checked with kubectls and the cmd `kubectl get policys.iam.aws.upbound.io` returns error, but `kubectl get policies.iam.aws.upbound.io` returns all policies created in a cluster.

EKS v1.28
Crossplane v1.14.5 (provider-aws-iam v1.1.1)

**Comment by undera** [comment]
Thanks for reporting this!
